[workspace]
members  = ["crates/message-defaults", "crates/message-nexus", "crates/message", "crates/message-meta"]
resolver = "3"

[workspace.package]
version      = "0.18.0"
edition      = "2024"
rust-version = "1.89"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/LiGoldragon/message"
publish      = false

[workspace.dependencies]
message-defaults    = { path = "crates/message-defaults" }
datom-codec         = { git = "https://github.com/LiGoldragon/datom-codec", rev = "4dff16b4f7412febc3b71aac8b49680cd20988cb" }
protos              = { git = "https://github.com/LiGoldragon/protos", rev = "15b41da8f2579e73ead59bc0c2b97529b8ac32d3" }
signal-message      = { git = "https://github.com/LiGoldragon/signal-message", rev = "0f5c0f0db88cf353606731f7d1ae0cdf6f49cd37" }
meta-signal-message = { git = "https://github.com/LiGoldragon/meta-signal-message", rev = "f8ca09fc91d4495b585c873938008553e2b94899" }
signal-flow         = { git = "https://github.com/LiGoldragon/signal-flow", rev = "c297d987c54968659f58fa85de129504850d0234" }
meta-signal-flow    = { git = "https://github.com/LiGoldragon/meta-signal-flow", rev = "69f9c146188a44979d2a870ada3b375ac04ac8b1" }
rkyv                = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
