use std::{io::Read, os::unix::net::UnixListener, time::Duration};
use message::{Configuration, MessageDaemon, MessengerTables, client::MessageSocket};
use signal_message::{AgentEndpoint, AgentEndpointBinding, AgentEndpointKind, AgentIdentityAssignment, MessageDaemonConfiguration, OwnerIdentity, ProcessPinSelection, PromptInterpretationSelection, PromptReceiptObservation, PromptRelayPermission, PromptRelayRejectionReason, PromptRelaySubmission, PromptVariant, Query, Response, ResumeSelection, TypedPromptEnvelope};
fn start_time() -> i64 { let s=std::fs::read_to_string("/proc/self/stat").unwrap(); s.rsplit_once(')').unwrap().1.split_whitespace().nth(17).unwrap().parse().unwrap() }
fn wait(path:&std::path::Path){let until=std::time::Instant::now()+Duration::from_secs(10);while !path.exists(){assert!(std::time::Instant::now()<until);std::thread::sleep(Duration::from_millis(10));}}
#[test]
fn prompt_ingress_uses_kernel_peer_and_observation_key() {
 let d=tempfile::tempdir().unwrap(); let ingress=d.path().join("prompt.sock"); let target=d.path().join("target.sock"); let id="self".to_string();
 let contract=MessageDaemonConfiguration { message_socket_path:d.path().join("message.sock").display().to_string(),message_socket_mode:0o600,supervision_socket_path:d.path().join("meta.sock").display().to_string(),supervision_socket_mode:0o600,router_socket_path:d.path().join("router.sock").display().to_string(),component_ingresses:vec![signal_message::ComponentMessageIngress { internal_component_instance_origin:signal_message::InternalComponentInstanceOrigin{component_name:signal_message::ComponentName::Harness,component_instance_name:"test".into()},ingress_socket_path:ingress.display().to_string(),socket_mode:0o600}],prompt_relay_permissions:vec![PromptRelayPermission{source_agent_identifier:id.clone(),destination_agent_identifier:id.clone()}],owner_identity:OwnerIdentity::UnixUser(rustix::process::getuid().as_raw().into())};
 let cfg=Configuration::new(contract,d.path().join("messenger.sema"),"test").unwrap(); let tables=MessengerTables::open(cfg.database_path()).unwrap(); tables.seat_identity(&AgentIdentityAssignment{agent_identifier:id.clone(),process_pin_selection:ProcessPinSelection::None,resume_selection:ResumeSelection::None}).unwrap(); tables.bind_endpoint(&AgentEndpointBinding{agent_identifier:id.clone(),agent_endpoint:AgentEndpoint{agent_endpoint_kind:AgentEndpointKind::HarnessSocket,endpoint_path:target.display().to_string()},harness_pid:std::process::id() as i64,harness_start_time:start_time()}).unwrap(); drop(tables); let cfgpath=d.path().join("cfg");cfg.write_binary_file(&cfgpath).unwrap(); let l=UnixListener::bind(&target).unwrap();let got=std::thread::spawn(move||{let(mut s,_)=l.accept().unwrap();let mut b=String::new();s.read_to_string(&mut b).unwrap();b});std::thread::spawn(move||MessageDaemon::from_configuration_path(&cfgpath).unwrap().run().unwrap());wait(&ingress);
 let q=Query::SubmitPrompt(PromptRelaySubmission{destination_agent_identifier:id.clone(),typed_prompt_envelope:TypedPromptEnvelope{prompt_variant:PromptVariant::HumanPrompt,source_event_identifier:"event".into(),raw_prompt_text:"raw".into(),prompt_interpretation_selection:PromptInterpretationSelection::None}}); let r=MessageSocket::from_path(&ingress).client().submit(q).unwrap();assert!(matches!(r,Response::PromptRelayAccepted(_)));assert_eq!(got.join().unwrap(),"raw");
 let r=MessageSocket::from_path(&ingress).client().submit(Query::ObservePromptReceipt(PromptReceiptObservation{destination_agent_identifier:id.clone(),source_event_identifier:"wrong".into()})).unwrap();assert!(matches!(r,Response::PromptRelayRejected(x) if x.prompt_relay_rejection_reason==PromptRelayRejectionReason::StoreRejected));
 let r=MessageSocket::from_path(&ingress).client().submit(Query::ObservePromptReceipt(PromptReceiptObservation{destination_agent_identifier:id,source_event_identifier:"event".into()})).unwrap();assert!(matches!(r,Response::PromptRelayAccepted(_)));
}
