// @generated by schema-rust-next
#[rustfmt::skip]
use thiserror::Error;
#[rustfmt::skip]
use triad_runtime::{
    AcceptedConnection, AsyncListenerError, AsyncConnectionRuntime,
    AsyncSingleListenerDaemon, AsyncSingleListenerDaemonError, ArgumentError,
    ComponentArgument, ComponentCommand, DaemonConfiguration, ExitReport, RequestErrorLog,
};
#[rustfmt::skip]
use triad_runtime::EngineRequestError;
#[rustfmt::skip]
use triad_runtime::kameo::Actor;
#[rustfmt::skip]
use triad_runtime::kameo::actor::{ActorRef, Spawn, WeakActorRef};
#[rustfmt::skip]
use triad_runtime::kameo::error::{ActorStopReason, HookError, SendError};
#[rustfmt::skip]
use triad_runtime::kameo::message::{Context, Message};
#[rustfmt::skip]
use tokio::io::AsyncWriteExt;
#[rustfmt::skip]
use triad_runtime::{FrameBody, FrameError, LengthPrefixedCodec};
#[rustfmt::skip]
use crate::schema::signal::{Input, Output, SignalFrameError};
#[rustfmt::skip]
/// The component hook surface for the emitted daemon — the only daemon
/// code the component hand-writes (record 1488 escape hatches).
///
/// The component declares its `Configuration` / `Engine` / `Error` types
/// and `PROCESS_NAME`, and provides the REQUIRED `build_runtime` (the
/// emitter cannot know how to open the component's Store/Engine) plus the
/// typed working-input handler.
pub trait ComponentDaemon: Sized + 'static {
    type Configuration: DaemonConfiguration;
    type ConfigurationError: std::error::Error;
    type Engine: Send + Sync + 'static;
    type Error: std::fmt::Debug
        + std::fmt::Display
        + From<FrameError>
        + From<SignalFrameError>
        + From<EngineRequestError>
        + Send
        + Sync
        + 'static;
    const PROCESS_NAME: &'static str;
    /// Load the binary rkyv `Configuration` from the daemon's single argument.
    fn load_configuration(
        path: &std::path::Path,
    ) -> Result<Self::Configuration, Self::ConfigurationError>;
    /// Open the component's durable Store and construct its Engine.
    fn build_runtime(
        configuration: &Self::Configuration,
    ) -> Result<Self::Engine, Self::Error>;
    /// Lifecycle: called once before the listener serves, once after it stops.
    fn start(engine: &Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    fn stop(engine: &Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    /// Run one decoded working `Input` through the engine and return the
    /// `Output` root to encode back to the caller.
    ///
    /// `connection` carries the accepted stream's kernel-vouched peer
    /// credentials (uid / gid / pid via `SO_PEERCRED`), so the component can
    /// mint an origin from the operating-system trust boundary rather than
    /// trusting a payload claim. Components that do not classify by origin
    /// take it as `_connection`.
    fn handle_working_input<'connection>(
        engine: &'connection mut Self::Engine,
        input: Input,
        connection: &'connection triad_runtime::ConnectionContext,
    ) -> impl std::future::Future<
        Output = Result<Output, Self::Error>,
    > + Send + 'connection;
}
#[rustfmt::skip]
/// argv -> binary `Configuration` -> the bound daemon. The single-argument
/// rule: exactly one argument, a signal-encoded (rkyv) configuration file.
pub struct DaemonCommand<Daemon: ComponentDaemon> {
    command: ComponentCommand,
    daemon: std::marker::PhantomData<fn() -> Daemon>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonCommand<Daemon> {
    pub fn from_environment() -> Self {
        Self {
            command: ComponentCommand::from_environment(),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn from_arguments<Arguments, Argument>(arguments: Arguments) -> Self
    where
        Arguments: IntoIterator<Item = Argument>,
        Argument: Into<String>,
    {
        Self {
            command: ComponentCommand::from_arguments(arguments),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn configuration(&self) -> Result<Daemon::Configuration, DaemonError<Daemon>> {
        match self.command.signal_file_argument()? {
            ComponentArgument::SignalFile(file) => {
                Daemon::load_configuration(file.as_path())
                    .map_err(DaemonError::Configuration)
            }
            ComponentArgument::InlineNota(_) | ComponentArgument::NotaFile(_) => {
                Err(DaemonError::Argument(ArgumentError::ExpectedSignalFile))
            }
        }
    }
    pub fn run(&self) -> Result<(), DaemonError<Daemon>> {
        tokio::runtime::Runtime::new()
            .map_err(DaemonError::Runtime)?
            .block_on(async {
                Daemon::bind(self.configuration()?)?
                    .run()
                    .await
                    .map_err(DaemonError::from)
            })
    }
}
#[rustfmt::skip]
/// The bound daemon constructor on the component trait: builds the engine,
/// wraps it in the generated actor connection runtime, and returns the
/// async task-backed listener shell the `DaemonCommand` drives. The component
/// never writes this by hand — it is emitted as a default method on
/// `ComponentDaemon`.
pub trait DaemonBinder: ComponentDaemon {
    fn bind(
        configuration: Self::Configuration,
    ) -> Result<
        AsyncSingleListenerDaemon<GeneratedDaemonRuntime<Self>>,
        DaemonError<Self>,
    > {
        let engine = Self::build_runtime(&configuration)
            .map_err(DaemonError::Component)?;
        let runtime = GeneratedDaemonRuntime::<Self>::new(engine);
        let daemon = AsyncSingleListenerDaemon::new(
                configuration.socket_path().to_path_buf(),
                runtime,
                RequestErrorLog::new(Self::PROCESS_NAME),
            )
            .with_concurrency_limit(configuration.request_concurrency_limit());
        Ok(
            match configuration.socket_mode() {
                Some(socket_mode) => daemon.with_socket_mode(socket_mode),
                None => daemon,
            },
        )
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonBinder for Daemon {}
#[rustfmt::skip]
/// The working-tier wire transport over one accepted stream: a
/// length-prefixed envelope around the schema-emitted signal frame codec.
struct WorkingTransport<'connection> {
    connection: &'connection mut AcceptedConnection,
}
#[rustfmt::skip]
impl<'connection> WorkingTransport<'connection> {
    fn new(connection: &'connection mut AcceptedConnection) -> Self {
        Self { connection }
    }
    fn context(&self) -> &triad_runtime::ConnectionContext {
        self.connection.context()
    }
    async fn read_frame(&mut self) -> Result<Vec<u8>, FrameError> {
        Ok(
            LengthPrefixedCodec::default()
                .read_body_async(self.connection.stream_mut())
                .await?
                .into_bytes(),
        )
    }
    async fn write_frame(&mut self, frame: Vec<u8>) -> Result<(), FrameError> {
        LengthPrefixedCodec::default()
            .write_body_async(self.connection.stream_mut(), &FrameBody::new(frame))
            .await?;
        self.connection.stream_mut().flush().await?;
        Ok(())
    }
}
#[rustfmt::skip]
/// The kameo actor that owns the component engine. The mailbox
/// serialises every request, giving each handler exclusive `&mut`
/// access to the engine without a component-internal lock.
pub struct EngineActor<Daemon: ComponentDaemon> {
    engine: Daemon::Engine,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Actor for EngineActor<Daemon> {
    type Args = Self;
    type Error = Daemon::Error;
    async fn on_start(
        actor: Self::Args,
        _actor_reference: ActorRef<Self>,
    ) -> Result<Self, Self::Error> {
        Daemon::start(&actor.engine)?;
        Ok(actor)
    }
    async fn on_stop(
        &mut self,
        _actor_reference: WeakActorRef<Self>,
        _reason: ActorStopReason,
    ) -> Result<(), Self::Error> {
        Daemon::stop(&self.engine)
    }
}
#[rustfmt::skip]
#[derive(Debug)]
pub struct WorkingInput {
    input: Input,
    context: triad_runtime::ConnectionContext,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Message<WorkingInput> for EngineActor<Daemon> {
    type Reply = Result<Output, Daemon::Error>;
    async fn handle(
        &mut self,
        message: WorkingInput,
        _context: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        Daemon::handle_working_input(&mut self.engine, message.input, &message.context)
            .await
    }
}
#[rustfmt::skip]
/// The generated runtime struct holds an `ActorRef` to the engine
/// actor. Its `handle_connection` IS the async decode -> ask -> encode
/// spine; the engine state lives behind the actor mailbox.
pub struct GeneratedDaemonRuntime<Daemon: ComponentDaemon> {
    engine: ActorRef<EngineActor<Daemon>>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> GeneratedDaemonRuntime<Daemon> {
    fn new(engine: Daemon::Engine) -> Self {
        Self {
            engine: EngineActor::<Daemon>::spawn(EngineActor { engine }),
        }
    }
    /// Translate a kameo `SendError` from an engine `ask` into the
    /// component's typed `Error` via `EngineRequestError`.
    fn engine_send_error(
        error: SendError<WorkingInput, Daemon::Error>,
    ) -> Daemon::Error {
        match error {
            SendError::HandlerError(error) => error,
            SendError::ActorNotRunning(_) => {
                EngineRequestError::new("engine actor is not running").into()
            }
            SendError::ActorStopped => {
                EngineRequestError::new("engine actor stopped before replying").into()
            }
            SendError::MailboxFull(_) => {
                EngineRequestError::new("engine actor mailbox is full").into()
            }
            SendError::Timeout(_) => {
                EngineRequestError::new("engine actor request timed out").into()
            }
        }
    }
    async fn handle_working_connection(
        &self,
        mut connection: AcceptedConnection,
    ) -> Result<(), Daemon::Error> {
        let mut transport = WorkingTransport::new(&mut connection);
        let frame = transport.read_frame().await?;
        let (_route, input) = Input::decode_signal_frame(&frame)?;
        let context = *transport.context();
        match self.engine.ask(WorkingInput { input, context }).await {
            Ok(output) => {
                transport.write_frame(output.encode_signal_frame()?).await?;
                Ok(())
            }
            Err(error) => Err(Self::engine_send_error(error)),
        }
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> AsyncConnectionRuntime for GeneratedDaemonRuntime<Daemon> {
    type Error = Daemon::Error;
    async fn start(&self) -> Result<(), Daemon::Error> {
        self.engine
            .wait_for_startup_with_result(|result| match result {
                Ok(()) => Ok(()),
                Err(HookError::Error(error)) => {
                    Err(
                        EngineRequestError::new(
                                format!("engine actor failed to start: {error:?}"),
                            )
                            .into(),
                    )
                }
                Err(HookError::Panicked(_)) => {
                    Err(
                        EngineRequestError::new("engine actor panicked during startup")
                            .into(),
                    )
                }
            })
            .await
    }
    async fn stop(&self) -> Result<(), Daemon::Error> {
        let _ = self.engine.stop_gracefully().await;
        self.engine.wait_for_shutdown().await;
        Ok(())
    }
    async fn handle_connection(
        &self,
        connection: AcceptedConnection,
    ) -> Result<(), Self::Error> {
        self.handle_working_connection(connection).await
    }
}
#[rustfmt::skip]
/// The emitted daemon error: argv, configuration, listener, and the
/// component error. The component's own error rides the `Component` arm.
#[derive(Debug, Error)]
pub enum DaemonError<Daemon: ComponentDaemon> {
    #[error("daemon argument error: {0}")]
    Argument(ArgumentError),
    #[error("daemon configuration error: {0}")]
    Configuration(Daemon::ConfigurationError),
    #[error("daemon runtime error: {0}")]
    Runtime(std::io::Error),
    #[error("daemon listener error: {0}")]
    Listener(AsyncListenerError),
    #[error("component error: {0}")]
    Component(Daemon::Error),
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> From<ArgumentError> for DaemonError<Daemon> {
    fn from(error: ArgumentError) -> Self {
        Self::Argument(error)
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> From<AsyncSingleListenerDaemonError<Daemon::Error>>
for DaemonError<Daemon> {
    fn from(error: AsyncSingleListenerDaemonError<Daemon::Error>) -> Self {
        match error {
            AsyncSingleListenerDaemonError::Listener(error) => Self::Listener(error),
            AsyncSingleListenerDaemonError::Start(error)
            | AsyncSingleListenerDaemonError::Stop(error) => Self::Component(error),
        }
    }
}
#[rustfmt::skip]
/// The component-agnostic exit body. The component's binary calls
/// `<SpiritDaemon as DaemonEntry>::run_to_exit_code()` from `fn main`.
pub trait DaemonEntry: ComponentDaemon {
    fn run_to_exit_code() -> std::process::ExitCode {
        ExitReport::new(Self::PROCESS_NAME)
            .from_result(DaemonCommand::<Self>::from_environment().run())
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonEntry for Daemon {}
