// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::Input as SignalInput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as SignalOutput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as MessageReply;
#[rustfmt::skip]
pub use crate::schema::signal::OperationKind as OperationKind;
#[rustfmt::skip]
pub use crate::schema::signal::UnimplementedReason as UnimplementedReason;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;
#[rustfmt::skip]
pub use crate::schema::signal::AgentRegistryCommand as RegistryCommand;
#[rustfmt::skip]
pub use crate::schema::signal::AgentRegistryQuery as RegistryQuery;
#[rustfmt::skip]
pub use crate::schema::signal::StoreCommand as StoreCommand;
#[rustfmt::skip]
pub use crate::schema::signal::StoreQuery as StoreQuery;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(SignalInput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectCompleted(NexusEffectResult);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(SignalOutput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandEffect(NexusEffectCommand);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusWork);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(ReplyToSignal),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    ApplyRegistry(ApplyRegistry),
    ReadRegistry(ReadRegistry),
    ApplyMessageStore(ApplyMessageStore),
    ReadMessageStore(ReadMessageStore),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplyRegistry(RegistryCommand);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadRegistry(RegistryQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplyMessageStore(StoreCommand);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadMessageStore(StoreQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegistryCompleted(MessageReply);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoreCompleted(MessageReply);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    RegistryCompleted(RegistryCompleted),
    StoreCompleted(StoreCompleted),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(ReplyToSignal),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: SignalInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalInput {
        &self.0
    }
    pub fn into_payload(self) -> SignalInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalInput> for SignalArrived {
    fn from(payload: SignalInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EffectCompleted {
    pub fn new(payload: NexusEffectResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectResult {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectResult> for EffectCompleted {
    fn from(payload: NexusEffectResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: SignalOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalOutput {
        &self.0
    }
    pub fn into_payload(self) -> SignalOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalOutput> for ReplyToSignal {
    fn from(payload: SignalOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandEffect {
    pub fn new(payload: NexusEffectCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectCommand {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectCommand> for CommandEffect {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusWork) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusWork {
        &self.0
    }
    pub fn into_payload(self) -> NexusWork {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusWork> for Continue {
    fn from(payload: NexusWork) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplyRegistry {
    pub fn new(payload: RegistryCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RegistryCommand {
        &self.0
    }
    pub fn into_payload(self) -> RegistryCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<RegistryCommand> for ApplyRegistry {
    fn from(payload: RegistryCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReadRegistry {
    pub fn new(payload: RegistryQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RegistryQuery {
        &self.0
    }
    pub fn into_payload(self) -> RegistryQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<RegistryQuery> for ReadRegistry {
    fn from(payload: RegistryQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplyMessageStore {
    pub fn new(payload: StoreCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreCommand {
        &self.0
    }
    pub fn into_payload(self) -> StoreCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreCommand> for ApplyMessageStore {
    fn from(payload: StoreCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReadMessageStore {
    pub fn new(payload: StoreQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreQuery {
        &self.0
    }
    pub fn into_payload(self) -> StoreQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreQuery> for ReadMessageStore {
    fn from(payload: StoreQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegistryCompleted {
    pub fn new(payload: MessageReply) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageReply {
        &self.0
    }
    pub fn into_payload(self) -> MessageReply {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageReply> for RegistryCompleted {
    fn from(payload: MessageReply) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoreCompleted {
    pub fn new(payload: MessageReply) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageReply {
        &self.0
    }
    pub fn into_payload(self) -> MessageReply {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageReply> for StoreCompleted {
    fn from(payload: MessageReply) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn apply_registry(payload: RegistryCommand) -> Self {
        Self::ApplyRegistry(ApplyRegistry::new(payload))
    }
    pub fn read_registry(payload: RegistryQuery) -> Self {
        Self::ReadRegistry(ReadRegistry::new(payload))
    }
    pub fn apply_message_store(payload: StoreCommand) -> Self {
        Self::ApplyMessageStore(ApplyMessageStore::new(payload))
    }
    pub fn read_message_store(payload: StoreQuery) -> Self {
        Self::ReadMessageStore(ReadMessageStore::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn registry_completed(payload: MessageReply) -> Self {
        Self::RegistryCompleted(RegistryCompleted::new(payload))
    }
    pub fn store_completed(payload: MessageReply) -> Self {
        Self::StoreCompleted(StoreCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusWork {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for NexusWork {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusAction {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for NexusAction {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusAction {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<ApplyRegistry> for NexusEffectCommand {
    fn from(payload: ApplyRegistry) -> Self {
        Self::ApplyRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<ReadRegistry> for NexusEffectCommand {
    fn from(payload: ReadRegistry) -> Self {
        Self::ReadRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<ApplyMessageStore> for NexusEffectCommand {
    fn from(payload: ApplyMessageStore) -> Self {
        Self::ApplyMessageStore(payload)
    }
}

#[rustfmt::skip]
impl From<ReadMessageStore> for NexusEffectCommand {
    fn from(payload: ReadMessageStore) -> Self {
        Self::ReadMessageStore(payload)
    }
}

#[rustfmt::skip]
impl From<RegistryCompleted> for NexusEffectResult {
    fn from(payload: RegistryCompleted) -> Self {
        Self::RegistryCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<StoreCompleted> for NexusEffectResult {
    fn from(payload: StoreCompleted) -> Self {
        Self::StoreCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for Input {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for Input {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for Output {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for Output {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for Output {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_ {
        async move {
            self.trace_nexus_entered();
            let output = self.decide(input);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
