// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    NoDurableState(NoDurableState),
}

#[rustfmt::skip]
pub type NoDurableState = Stateless;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    NoDurableState(NoDurableState),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    Stateless(Stateless),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    Stateless(Stateless),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stateless {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    WriteInput(WriteInput),
    ReadInput(ReadInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    WriteOutput(WriteOutput),
    ReadOutput(ReadOutput),
}

#[rustfmt::skip]
impl WriteInput {
    pub fn no_durable_state(payload: NoDurableState) -> Self {
        Self::NoDurableState(payload)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn no_durable_state(payload: NoDurableState) -> Self {
        Self::NoDurableState(payload)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn stateless(payload: Stateless) -> Self {
        Self::Stateless(payload)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn stateless(payload: Stateless) -> Self {
        Self::Stateless(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<Stateless> for WriteOutput {
    fn from(payload: Stateless) -> Self {
        Self::Stateless(payload)
    }
}

#[rustfmt::skip]
impl From<Stateless> for ReadOutput {
    fn from(payload: Stateless) -> Self {
        Self::Stateless(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Stateless {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    NoDurableState,
}

#[rustfmt::skip]
impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::NoDurableState(_) => WriteInputRoute::NoDurableState,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    NoDurableState,
}

#[rustfmt::skip]
impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::NoDurableState(_) => ReadInputRoute::NoDurableState,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    Stateless,
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::Stateless(_) => WriteOutputRoute::Stateless,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    Stateless,
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::Stateless(_) => ReadOutputRoute::Stateless,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::NoDurableState => "SemaWriteInputNoDurableState",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::NoDurableState => "SemaReadInputNoDurableState",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::Stateless => "SemaWriteOutputStateless",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::Stateless => "SemaReadOutputStateless",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for WriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for WriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for ReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for ReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
