// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Submit(MessageSubmission);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmitStamped(StampedMessageSubmission);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QueryInbox(InboxQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AssignAgentIdentity(AgentIdentityAssignment);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BindAgentEndpoint(AgentEndpointBinding);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QueryAgentRegistry(AgentRegistryQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionAccepted(SubmissionAcceptance);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionRejected(SubmissionRejection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxListing(InboxContents);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentityAssigned(AssignedAgentIdentity);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpointBound(BoundAgentEndpoint);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryListing(AgentRegistryEntries);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryRejected(AgentRegistryRejection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Unimplemented(RequestUnimplemented);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Error(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Recipient(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sender(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Body(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSlot(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OwnerName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanos(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorMessage(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageKind {
    Send,
    Inbox,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Kind(MessageKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ThreadSelection {
    None,
    Named(ThreadName),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSubmission {
    pub recipient: Recipient,
    pub kind: Kind,
    pub body: Body,
    pub thread_selection: ThreadSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser,
    InternalComponentInstance,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageOrigin {
    pub connection_class: ConnectionClass,
    pub owner_name: OwnerName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Submission(MessageSubmission);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Origin(MessageOrigin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StampedAt(TimestampNanos);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StampedMessageSubmission {
    pub submission: Submission,
    pub origin: Origin,
    pub stamped_at: StampedAt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxQuery(Recipient);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxEntry {
    pub message_slot: MessageSlot,
    pub sender: Sender,
    pub body: Body,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxEntries(Vec<InboxEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxContents(InboxEntries);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionAcceptance(MessageSlot);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SubmissionRejectionReason {
    StoreRejected,
    RecipientNotFound,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionRejection(SubmissionRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Submit,
    SubmitStamped,
    QueryInbox,
    AssignAgentIdentity,
    BindAgentEndpoint,
    QueryAgentRegistry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
    RouterUnreachable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessPid(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessStartTime(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResumeIdentity(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ResumeSelection {
    None,
    Resumed(ResumeIdentity),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentEndpointKind {
    PtySocket,
    HarnessSocket,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EndpointPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpoint {
    pub agent_endpoint_kind: AgentEndpointKind,
    pub endpoint_path: EndpointPath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EndpointSelection {
    None,
    Bound(AgentEndpoint),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentDeathMark {
    NotDead,
    Killed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentityAssignment {
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
    pub resume_selection: ResumeSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IdentityProvenance {
    Minted,
    Reused,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AssignedAgentIdentity {
    pub agent_identifier: AgentIdentifier,
    pub identity_provenance: IdentityProvenance,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpointBinding {
    pub agent_identifier: AgentIdentifier,
    pub agent_endpoint: AgentEndpoint,
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BoundAgentEndpoint(AgentIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AgentRegistryQuery {
    All,
    ByAgent(AgentIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryEntry {
    pub agent_identifier: AgentIdentifier,
    pub endpoint_selection: EndpointSelection,
    pub resume_selection: ResumeSelection,
    pub agent_death_mark: AgentDeathMark,
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryEntries(Vec<AgentRegistryEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentRegistryRejectionReason {
    UnknownAgentIdentifier,
    IdentifierSpanExhausted,
    StoreRejected,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryRejection(AgentRegistryRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AgentRegistryCommand {
    AssignIdentity(AgentIdentityAssignment),
    BindEndpoint(AgentEndpointBinding),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnimplementedOperationKind(OperationKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reason(UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented {
    pub unimplemented_operation_kind: UnimplementedOperationKind,
    pub reason: Reason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport(ErrorMessage);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Submit(Submit),
    SubmitStamped(SubmitStamped),
    QueryInbox(QueryInbox),
    AssignAgentIdentity(AssignAgentIdentity),
    BindAgentEndpoint(BindAgentEndpoint),
    QueryAgentRegistry(QueryAgentRegistry),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SubmissionAccepted(SubmissionAccepted),
    SubmissionRejected(SubmissionRejected),
    InboxListing(InboxListing),
    AgentIdentityAssigned(AgentIdentityAssigned),
    AgentEndpointBound(AgentEndpointBound),
    AgentRegistryListing(AgentRegistryListing),
    AgentRegistryRejected(AgentRegistryRejected),
    Unimplemented(Unimplemented),
    Error(Error),
}

#[rustfmt::skip]
impl Submit {
    pub fn new(payload: MessageSubmission) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageSubmission {
        &self.0
    }
    pub fn into_payload(self) -> MessageSubmission {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageSubmission> for Submit {
    fn from(payload: MessageSubmission) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmitStamped {
    pub fn new(payload: StampedMessageSubmission) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StampedMessageSubmission {
        &self.0
    }
    pub fn into_payload(self) -> StampedMessageSubmission {
        self.0
    }
}
#[rustfmt::skip]
impl From<StampedMessageSubmission> for SubmitStamped {
    fn from(payload: StampedMessageSubmission) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl QueryInbox {
    pub fn new(payload: InboxQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InboxQuery {
        &self.0
    }
    pub fn into_payload(self) -> InboxQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<InboxQuery> for QueryInbox {
    fn from(payload: InboxQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AssignAgentIdentity {
    pub fn new(payload: AgentIdentityAssignment) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentIdentityAssignment {
        &self.0
    }
    pub fn into_payload(self) -> AgentIdentityAssignment {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentIdentityAssignment> for AssignAgentIdentity {
    fn from(payload: AgentIdentityAssignment) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BindAgentEndpoint {
    pub fn new(payload: AgentEndpointBinding) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentEndpointBinding {
        &self.0
    }
    pub fn into_payload(self) -> AgentEndpointBinding {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentEndpointBinding> for BindAgentEndpoint {
    fn from(payload: AgentEndpointBinding) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl QueryAgentRegistry {
    pub fn new(payload: AgentRegistryQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentRegistryQuery {
        &self.0
    }
    pub fn into_payload(self) -> AgentRegistryQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentRegistryQuery> for QueryAgentRegistry {
    fn from(payload: AgentRegistryQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionAccepted {
    pub fn new(payload: SubmissionAcceptance) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubmissionAcceptance {
        &self.0
    }
    pub fn into_payload(self) -> SubmissionAcceptance {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubmissionAcceptance> for SubmissionAccepted {
    fn from(payload: SubmissionAcceptance) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionRejected {
    pub fn new(payload: SubmissionRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubmissionRejection {
        &self.0
    }
    pub fn into_payload(self) -> SubmissionRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubmissionRejection> for SubmissionRejected {
    fn from(payload: SubmissionRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxListing {
    pub fn new(payload: InboxContents) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InboxContents {
        &self.0
    }
    pub fn into_payload(self) -> InboxContents {
        self.0
    }
}
#[rustfmt::skip]
impl From<InboxContents> for InboxListing {
    fn from(payload: InboxContents) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentIdentityAssigned {
    pub fn new(payload: AssignedAgentIdentity) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AssignedAgentIdentity {
        &self.0
    }
    pub fn into_payload(self) -> AssignedAgentIdentity {
        self.0
    }
}
#[rustfmt::skip]
impl From<AssignedAgentIdentity> for AgentIdentityAssigned {
    fn from(payload: AssignedAgentIdentity) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentEndpointBound {
    pub fn new(payload: BoundAgentEndpoint) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &BoundAgentEndpoint {
        &self.0
    }
    pub fn into_payload(self) -> BoundAgentEndpoint {
        self.0
    }
}
#[rustfmt::skip]
impl From<BoundAgentEndpoint> for AgentEndpointBound {
    fn from(payload: BoundAgentEndpoint) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryListing {
    pub fn new(payload: AgentRegistryEntries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentRegistryEntries {
        &self.0
    }
    pub fn into_payload(self) -> AgentRegistryEntries {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentRegistryEntries> for AgentRegistryListing {
    fn from(payload: AgentRegistryEntries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryRejected {
    pub fn new(payload: AgentRegistryRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentRegistryRejection {
        &self.0
    }
    pub fn into_payload(self) -> AgentRegistryRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentRegistryRejection> for AgentRegistryRejected {
    fn from(payload: AgentRegistryRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Unimplemented {
    pub fn new(payload: RequestUnimplemented) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RequestUnimplemented {
        &self.0
    }
    pub fn into_payload(self) -> RequestUnimplemented {
        self.0
    }
}
#[rustfmt::skip]
impl From<RequestUnimplemented> for Unimplemented {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Error {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for Error {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Recipient {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Recipient {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Sender {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Sender {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Body {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Body {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSlot {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MessageSlot {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OwnerName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for OwnerName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanos {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TimestampNanos {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ErrorMessage {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ErrorMessage {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Kind {
    pub fn new(payload: MessageKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageKind {
        &self.0
    }
    pub fn into_payload(self) -> MessageKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageKind> for Kind {
    fn from(payload: MessageKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ThreadName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Submission {
    pub fn new(payload: MessageSubmission) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageSubmission {
        &self.0
    }
    pub fn into_payload(self) -> MessageSubmission {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageSubmission> for Submission {
    fn from(payload: MessageSubmission) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Origin {
    pub fn new(payload: MessageOrigin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageOrigin {
        &self.0
    }
    pub fn into_payload(self) -> MessageOrigin {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageOrigin> for Origin {
    fn from(payload: MessageOrigin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StampedAt {
    pub fn new(payload: TimestampNanos) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TimestampNanos {
        &self.0
    }
    pub fn into_payload(self) -> TimestampNanos {
        self.0
    }
}
#[rustfmt::skip]
impl From<TimestampNanos> for StampedAt {
    fn from(payload: TimestampNanos) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxQuery {
    pub fn new(payload: Recipient) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Recipient {
        &self.0
    }
    pub fn into_payload(self) -> Recipient {
        self.0
    }
}
#[rustfmt::skip]
impl From<Recipient> for InboxQuery {
    fn from(payload: Recipient) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxEntries {
    pub fn new(payload: Vec<InboxEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<InboxEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<InboxEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<InboxEntry>> for InboxEntries {
    fn from(payload: Vec<InboxEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxContents {
    pub fn new(payload: InboxEntries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InboxEntries {
        &self.0
    }
    pub fn into_payload(self) -> InboxEntries {
        self.0
    }
}
#[rustfmt::skip]
impl From<InboxEntries> for InboxContents {
    fn from(payload: InboxEntries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionAcceptance {
    pub fn new(payload: MessageSlot) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageSlot {
        &self.0
    }
    pub fn into_payload(self) -> MessageSlot {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageSlot> for SubmissionAcceptance {
    fn from(payload: MessageSlot) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionRejection {
    pub fn new(payload: SubmissionRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubmissionRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> SubmissionRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubmissionRejectionReason> for SubmissionRejection {
    fn from(payload: SubmissionRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AgentIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HarnessPid {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for HarnessPid {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HarnessStartTime {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for HarnessStartTime {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ResumeIdentity {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ResumeIdentity {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EndpointPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EndpointPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BoundAgentEndpoint {
    pub fn new(payload: AgentIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> AgentIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentIdentifier> for BoundAgentEndpoint {
    fn from(payload: AgentIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryEntries {
    pub fn new(payload: Vec<AgentRegistryEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<AgentRegistryEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<AgentRegistryEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<AgentRegistryEntry>> for AgentRegistryEntries {
    fn from(payload: Vec<AgentRegistryEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryRejection {
    pub fn new(payload: AgentRegistryRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentRegistryRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> AgentRegistryRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentRegistryRejectionReason> for AgentRegistryRejection {
    fn from(payload: AgentRegistryRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnimplementedOperationKind {
    pub fn new(payload: OperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OperationKind {
        &self.0
    }
    pub fn into_payload(self) -> OperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<OperationKind> for UnimplementedOperationKind {
    fn from(payload: OperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Reason {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for Reason {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ErrorReport {
    pub fn new(payload: ErrorMessage) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorMessage {
        &self.0
    }
    pub fn into_payload(self) -> ErrorMessage {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorMessage> for ErrorReport {
    fn from(payload: ErrorMessage) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadSelection {
    pub fn named(payload: String) -> Self {
        Self::Named(ThreadName::new(payload))
    }
}

#[rustfmt::skip]
impl ResumeSelection {
    pub fn resumed(payload: String) -> Self {
        Self::Resumed(ResumeIdentity::new(payload))
    }
}

#[rustfmt::skip]
impl EndpointSelection {
    pub fn bound(payload: AgentEndpoint) -> Self {
        Self::Bound(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryQuery {
    pub fn by_agent(payload: String) -> Self {
        Self::ByAgent(AgentIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl AgentRegistryCommand {
    pub fn assign_identity(payload: AgentIdentityAssignment) -> Self {
        Self::AssignIdentity(payload)
    }
    pub fn bind_endpoint(payload: AgentEndpointBinding) -> Self {
        Self::BindEndpoint(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn submit(payload: MessageSubmission) -> Self {
        Self::Submit(Submit::new(payload))
    }
    pub fn submit_stamped(payload: StampedMessageSubmission) -> Self {
        Self::SubmitStamped(SubmitStamped::new(payload))
    }
    pub fn query_inbox(payload: InboxQuery) -> Self {
        Self::QueryInbox(QueryInbox::new(payload))
    }
    pub fn assign_agent_identity(payload: AgentIdentityAssignment) -> Self {
        Self::AssignAgentIdentity(AssignAgentIdentity::new(payload))
    }
    pub fn bind_agent_endpoint(payload: AgentEndpointBinding) -> Self {
        Self::BindAgentEndpoint(BindAgentEndpoint::new(payload))
    }
    pub fn query_agent_registry(payload: AgentRegistryQuery) -> Self {
        Self::QueryAgentRegistry(QueryAgentRegistry::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn submission_accepted(payload: SubmissionAcceptance) -> Self {
        Self::SubmissionAccepted(SubmissionAccepted::new(payload))
    }
    pub fn submission_rejected(payload: SubmissionRejection) -> Self {
        Self::SubmissionRejected(SubmissionRejected::new(payload))
    }
    pub fn inbox_listing(payload: InboxContents) -> Self {
        Self::InboxListing(InboxListing::new(payload))
    }
    pub fn agent_identity_assigned(payload: AssignedAgentIdentity) -> Self {
        Self::AgentIdentityAssigned(AgentIdentityAssigned::new(payload))
    }
    pub fn agent_endpoint_bound(payload: BoundAgentEndpoint) -> Self {
        Self::AgentEndpointBound(AgentEndpointBound::new(payload))
    }
    pub fn agent_registry_listing(payload: AgentRegistryEntries) -> Self {
        Self::AgentRegistryListing(AgentRegistryListing::new(payload))
    }
    pub fn agent_registry_rejected(payload: AgentRegistryRejection) -> Self {
        Self::AgentRegistryRejected(AgentRegistryRejected::new(payload))
    }
    pub fn unimplemented(payload: RequestUnimplemented) -> Self {
        Self::Unimplemented(Unimplemented::new(payload))
    }
    pub fn error(payload: ErrorReport) -> Self {
        Self::Error(Error::new(payload))
    }
}

#[rustfmt::skip]
impl From<ThreadName> for ThreadSelection {
    fn from(payload: ThreadName) -> Self {
        Self::Named(payload)
    }
}

#[rustfmt::skip]
impl From<ResumeIdentity> for ResumeSelection {
    fn from(payload: ResumeIdentity) -> Self {
        Self::Resumed(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpoint> for EndpointSelection {
    fn from(payload: AgentEndpoint) -> Self {
        Self::Bound(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentifier> for AgentRegistryQuery {
    fn from(payload: AgentIdentifier) -> Self {
        Self::ByAgent(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentityAssignment> for AgentRegistryCommand {
    fn from(payload: AgentIdentityAssignment) -> Self {
        Self::AssignIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpointBinding> for AgentRegistryCommand {
    fn from(payload: AgentEndpointBinding) -> Self {
        Self::BindEndpoint(payload)
    }
}

#[rustfmt::skip]
impl From<Submit> for Input {
    fn from(payload: Submit) -> Self {
        Self::Submit(payload)
    }
}

#[rustfmt::skip]
impl From<SubmitStamped> for Input {
    fn from(payload: SubmitStamped) -> Self {
        Self::SubmitStamped(payload)
    }
}

#[rustfmt::skip]
impl From<QueryInbox> for Input {
    fn from(payload: QueryInbox) -> Self {
        Self::QueryInbox(payload)
    }
}

#[rustfmt::skip]
impl From<AssignAgentIdentity> for Input {
    fn from(payload: AssignAgentIdentity) -> Self {
        Self::AssignAgentIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<BindAgentEndpoint> for Input {
    fn from(payload: BindAgentEndpoint) -> Self {
        Self::BindAgentEndpoint(payload)
    }
}

#[rustfmt::skip]
impl From<QueryAgentRegistry> for Input {
    fn from(payload: QueryAgentRegistry) -> Self {
        Self::QueryAgentRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<SubmissionAccepted> for Output {
    fn from(payload: SubmissionAccepted) -> Self {
        Self::SubmissionAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<SubmissionRejected> for Output {
    fn from(payload: SubmissionRejected) -> Self {
        Self::SubmissionRejected(payload)
    }
}

#[rustfmt::skip]
impl From<InboxListing> for Output {
    fn from(payload: InboxListing) -> Self {
        Self::InboxListing(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentityAssigned> for Output {
    fn from(payload: AgentIdentityAssigned) -> Self {
        Self::AgentIdentityAssigned(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpointBound> for Output {
    fn from(payload: AgentEndpointBound) -> Self {
        Self::AgentEndpointBound(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryListing> for Output {
    fn from(payload: AgentRegistryListing) -> Self {
        Self::AgentRegistryListing(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryRejected> for Output {
    fn from(payload: AgentRegistryRejected) -> Self {
        Self::AgentRegistryRejected(payload)
    }
}

#[rustfmt::skip]
impl From<Unimplemented> for Output {
    fn from(payload: Unimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<Error> for Output {
    fn from(payload: Error) -> Self {
        Self::Error(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_SUBMIT: u64 = 0x0000000000000000;
    pub const INPUT_SUBMIT_STAMPED: u64 = 0x0001000000000000;
    pub const INPUT_QUERY_INBOX: u64 = 0x0002000000000000;
    pub const INPUT_ASSIGN_AGENT_IDENTITY: u64 = 0x0003000000000000;
    pub const INPUT_BIND_AGENT_ENDPOINT: u64 = 0x0004000000000000;
    pub const INPUT_QUERY_AGENT_REGISTRY: u64 = 0x0005000000000000;
    pub const OUTPUT_SUBMISSION_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_SUBMISSION_REJECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_INBOX_LISTING: u64 = 0x0102000000000000;
    pub const OUTPUT_AGENT_IDENTITY_ASSIGNED: u64 = 0x0103000000000000;
    pub const OUTPUT_AGENT_ENDPOINT_BOUND: u64 = 0x0104000000000000;
    pub const OUTPUT_AGENT_REGISTRY_LISTING: u64 = 0x0105000000000000;
    pub const OUTPUT_AGENT_REGISTRY_REJECTED: u64 = 0x0106000000000000;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x0107000000000000;
    pub const OUTPUT_ERROR: u64 = 0x0108000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Submit,
    SubmitStamped,
    QueryInbox,
    AssignAgentIdentity,
    BindAgentEndpoint,
    QueryAgentRegistry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SubmissionAccepted,
    SubmissionRejected,
    InboxListing,
    AgentIdentityAssigned,
    AgentEndpointBound,
    AgentRegistryListing,
    AgentRegistryRejected,
    Unimplemented,
    Error,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Submit(_) => InputRoute::Submit,
            Self::SubmitStamped(_) => InputRoute::SubmitStamped,
            Self::QueryInbox(_) => InputRoute::QueryInbox,
            Self::AssignAgentIdentity(_) => InputRoute::AssignAgentIdentity,
            Self::BindAgentEndpoint(_) => InputRoute::BindAgentEndpoint,
            Self::QueryAgentRegistry(_) => InputRoute::QueryAgentRegistry,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Submit(_) => short_header::INPUT_SUBMIT,
            Self::SubmitStamped(_) => short_header::INPUT_SUBMIT_STAMPED,
            Self::QueryInbox(_) => short_header::INPUT_QUERY_INBOX,
            Self::AssignAgentIdentity(_) => short_header::INPUT_ASSIGN_AGENT_IDENTITY,
            Self::BindAgentEndpoint(_) => short_header::INPUT_BIND_AGENT_ENDPOINT,
            Self::QueryAgentRegistry(_) => short_header::INPUT_QUERY_AGENT_REGISTRY,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_SUBMIT => Ok(InputRoute::Submit),
            short_header::INPUT_SUBMIT_STAMPED => Ok(InputRoute::SubmitStamped),
            short_header::INPUT_QUERY_INBOX => Ok(InputRoute::QueryInbox),
            short_header::INPUT_ASSIGN_AGENT_IDENTITY => {
                Ok(InputRoute::AssignAgentIdentity)
            }
            short_header::INPUT_BIND_AGENT_ENDPOINT => Ok(InputRoute::BindAgentEndpoint),
            short_header::INPUT_QUERY_AGENT_REGISTRY => {
                Ok(InputRoute::QueryAgentRegistry)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SubmissionAccepted(_) => OutputRoute::SubmissionAccepted,
            Self::SubmissionRejected(_) => OutputRoute::SubmissionRejected,
            Self::InboxListing(_) => OutputRoute::InboxListing,
            Self::AgentIdentityAssigned(_) => OutputRoute::AgentIdentityAssigned,
            Self::AgentEndpointBound(_) => OutputRoute::AgentEndpointBound,
            Self::AgentRegistryListing(_) => OutputRoute::AgentRegistryListing,
            Self::AgentRegistryRejected(_) => OutputRoute::AgentRegistryRejected,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
            Self::Error(_) => OutputRoute::Error,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SubmissionAccepted(_) => short_header::OUTPUT_SUBMISSION_ACCEPTED,
            Self::SubmissionRejected(_) => short_header::OUTPUT_SUBMISSION_REJECTED,
            Self::InboxListing(_) => short_header::OUTPUT_INBOX_LISTING,
            Self::AgentIdentityAssigned(_) => {
                short_header::OUTPUT_AGENT_IDENTITY_ASSIGNED
            }
            Self::AgentEndpointBound(_) => short_header::OUTPUT_AGENT_ENDPOINT_BOUND,
            Self::AgentRegistryListing(_) => short_header::OUTPUT_AGENT_REGISTRY_LISTING,
            Self::AgentRegistryRejected(_) => {
                short_header::OUTPUT_AGENT_REGISTRY_REJECTED
            }
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
            Self::Error(_) => short_header::OUTPUT_ERROR,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SUBMISSION_ACCEPTED => {
                Ok(OutputRoute::SubmissionAccepted)
            }
            short_header::OUTPUT_SUBMISSION_REJECTED => {
                Ok(OutputRoute::SubmissionRejected)
            }
            short_header::OUTPUT_INBOX_LISTING => Ok(OutputRoute::InboxListing),
            short_header::OUTPUT_AGENT_IDENTITY_ASSIGNED => {
                Ok(OutputRoute::AgentIdentityAssigned)
            }
            short_header::OUTPUT_AGENT_ENDPOINT_BOUND => {
                Ok(OutputRoute::AgentEndpointBound)
            }
            short_header::OUTPUT_AGENT_REGISTRY_LISTING => {
                Ok(OutputRoute::AgentRegistryListing)
            }
            short_header::OUTPUT_AGENT_REGISTRY_REJECTED => {
                Ok(OutputRoute::AgentRegistryRejected)
            }
            short_header::OUTPUT_UNIMPLEMENTED => Ok(OutputRoute::Unimplemented),
            short_header::OUTPUT_ERROR => Ok(OutputRoute::Error),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Submit",
        "SubmitStamped",
        "QueryInbox",
        "AssignAgentIdentity",
        "BindAgentEndpoint",
        "QueryAgentRegistry",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
    Started,
    Stopped,
    Admitted,
    Rejected,
    Triaged,
    Replied,
}
#[rustfmt::skip]
impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => {
                match route {
                    InputRoute::Submit => "SignalInputSubmit",
                    InputRoute::SubmitStamped => "SignalInputSubmitStamped",
                    InputRoute::QueryInbox => "SignalInputQueryInbox",
                    InputRoute::AssignAgentIdentity => "SignalInputAssignAgentIdentity",
                    InputRoute::BindAgentEndpoint => "SignalInputBindAgentEndpoint",
                    InputRoute::QueryAgentRegistry => "SignalInputQueryAgentRegistry",
                }
            }
            Self::Output(route) => {
                match route {
                    OutputRoute::SubmissionAccepted => "SignalOutputSubmissionAccepted",
                    OutputRoute::SubmissionRejected => "SignalOutputSubmissionRejected",
                    OutputRoute::InboxListing => "SignalOutputInboxListing",
                    OutputRoute::AgentIdentityAssigned => {
                        "SignalOutputAgentIdentityAssigned"
                    }
                    OutputRoute::AgentEndpointBound => "SignalOutputAgentEndpointBound",
                    OutputRoute::AgentRegistryListing => {
                        "SignalOutputAgentRegistryListing"
                    }
                    OutputRoute::AgentRegistryRejected => {
                        "SignalOutputAgentRegistryRejected"
                    }
                    OutputRoute::Unimplemented => "SignalOutputUnimplemented",
                    OutputRoute::Error => "SignalOutputError",
                }
            }
            Self::Started => "SignalStarted",
            Self::Stopped => "SignalStopped",
            Self::Admitted => "SignalAdmitted",
            Self::Rejected => "SignalRejected",
            Self::Triaged => "SignalTriaged",
            Self::Replied => "SignalReplied",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Signal(SignalObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct MessageIdentifier(Integer);
#[rustfmt::skip]
impl MessageIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageRoot {
    Input,
    Output,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}
#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}
#[rustfmt::skip]
pub trait MessageSentHook {
    type Error;
    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
pub trait MessageProcessedHook<Reply> {
    type Error;
    fn message_processed(
        &mut self,
        event: MessageProcessed<Reply>,
    ) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}
#[rustfmt::skip]
impl<Reply> MessageProcessed<Reply> {
    pub fn new(
        identifier: MessageIdentifier,
        origin_route: OriginRoute,
        reply: Reply,
    ) -> Self {
        Self {
            identifier,
            origin_route,
            reply,
        }
    }
    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn into_reply(self) -> Reply {
        self.reply
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}
#[rustfmt::skip]
impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}
#[rustfmt::skip]
impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SignalEngine: Send {
    type NexusInput;
    type NexusOutput;
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_signal_activation(&self, _object_name: SignalObjectName) {}
    fn trace_signal_admitted(&self) {
        self.trace_signal_activation(SignalObjectName::Admitted);
    }
    fn trace_signal_rejected(&self) {
        self.trace_signal_activation(SignalObjectName::Rejected);
    }
    fn trace_signal_triaged(&self) {
        self.trace_signal_activation(SignalObjectName::Triaged);
    }
    fn trace_signal_replied(&self) {
        self.trace_signal_activation(SignalObjectName::Replied);
    }
    fn triage_inner(&self, input: signal::Signal<signal::Input>) -> Self::NexusInput;
    fn reply_inner(&self, output: Self::NexusOutput) -> signal::Signal<signal::Output>;
    fn triage(&self, input: signal::Signal<signal::Input>) -> Self::NexusInput {
        let output = self.triage_inner(input);
        self.trace_signal_triaged();
        output
    }
    fn reply(&self, output: Self::NexusOutput) -> signal::Signal<signal::Output> {
        let signal_output = self.reply_inner(output);
        self.trace_signal_replied();
        signal_output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
